.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-profile-set-api-key 1  "set-api-key "
.SH NAME
temporal\-tui\-profile\-set\-api\-key \- Read an API key without echo and store it in the OS credential manager
.SH SYNOPSIS
\fBtemporal\-tui profile set\-api\-key\fR [\fB\-\-config\fR] [\fB\-\-from\-env\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR>
.SH DESCRIPTION
Read an API key without echo and store it in the OS credential manager
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-from\-env\fR \fI<FROM_ENV>\fR
Read the API key from this environment variable instead of prompting
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
