.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-profile-remove 1  "remove "
.SH NAME
temporal\-tui\-profile\-remove \- Remove a profile
.SH SYNOPSIS
\fBtemporal\-tui profile remove\fR [\fB\-\-config\fR] [\fB\-\-yes\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR>
.SH DESCRIPTION
Remove a profile
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-yes\fR

.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
