.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-config-path 1  "config-path "
.SH NAME
temporal\-tui\-config\-path \- Print the active config path
.SH SYNOPSIS
\fBtemporal\-tui config\-path\fR [\fB\-\-config\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Print the active config path
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
