.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-profile-create 1  "create "
.SH NAME
temporal\-tui\-profile\-create \- Create a connection profile
.SH SYNOPSIS
\fBtemporal\-tui profile create\fR <\fB\-\-address\fR> [\fB\-\-config\fR] [\fB\-n\fR|\fB\-\-namespace\fR] [\fB\-\-profile\fR] [\fB\-\-tls\fR] [\fB\-\-tls\-ca\fR] [\fB\-\-tls\-cert\fR] [\fB\-\-tls\-key\fR] [\fB\-\-tls\-server\-name\fR] [\fB\-\-header\fR] [\fB\-\-codec\-endpoint\fR] [\fB\-\-codec\-header\fR] [\fB\-\-codec\-auth\-env\fR] [\fB\-\-api\-key\-env\fR] [\fB\-\-web\-ui\-url\fR] [\fB\-\-read\-only\fR] [\fB\-\-set\-default\fR] [\fB\-\-replace\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR>
.SH DESCRIPTION
Create a connection profile
.SH OPTIONS
.TP
\fB\-\-address\fR \fI<ADDRESS>\fR

.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-n\fR, \fB\-\-namespace\fR \fI<NAMESPACE>\fR [default: default]

.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-\-tls\fR

.TP
\fB\-\-tls\-ca\fR \fI<TLS_CA>\fR

.TP
\fB\-\-tls\-cert\fR \fI<TLS_CERT>\fR

.TP
\fB\-\-tls\-key\fR \fI<TLS_KEY>\fR

.TP
\fB\-\-tls\-server\-name\fR \fI<TLS_SERVER_NAME>\fR

.TP
\fB\-\-header\fR \fI<HEADERS>\fR

.TP
\fB\-\-codec\-endpoint\fR \fI<CODEC_ENDPOINT>\fR

.TP
\fB\-\-codec\-header\fR \fI<CODEC_HEADERS>\fR

.TP
\fB\-\-codec\-auth\-env\fR \fI<CODEC_AUTH_ENV>\fR

.TP
\fB\-\-api\-key\-env\fR \fI<API_KEY_ENV>\fR

.TP
\fB\-\-web\-ui\-url\fR \fI<WEB_UI_URL>\fR

.TP
\fB\-\-read\-only\fR

.TP
\fB\-\-set\-default\fR

.TP
\fB\-\-replace\fR
Replace an existing profile with the same name
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
