.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-filter-save 1  "save "
.SH NAME
temporal\-tui\-filter\-save \- Save or replace a visibility query
.SH SYNOPSIS
\fBtemporal\-tui filter save\fR [\fB\-\-config\fR] [\fB\-\-replace\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> <\fIQUERY\fR>
.SH DESCRIPTION
Save or replace a visibility query
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-replace\fR

.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

.TP
<\fIQUERY\fR>
