.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-auth-whoami 1  "whoami "
.SH NAME
temporal\-tui\-auth\-whoami \- Show the current signed\-in identity and session status
.SH SYNOPSIS
\fBtemporal\-tui auth whoami\fR [\fB\-\-config\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Show the current signed\-in identity and session status
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
