.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-filter-list 1  "list "
.SH NAME
temporal\-tui\-filter\-list \- List saved visibility queries
.SH SYNOPSIS
\fBtemporal\-tui filter list\fR [\fB\-\-config\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List saved visibility queries
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
