.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH temporal-tui-filter 1  "filter "
.SH NAME
temporal\-tui\-filter \- Manage saved visibility queries
.SH SYNOPSIS
\fBtemporal\-tui filter\fR [\fB\-\-config\fR] [\fB\-\-profile\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage saved visibility queries
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
Alternate config file. Defaults to the platform user config directory
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR
Named connection profile
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
temporal\-tui\-filter\-list(1)
List saved visibility queries
.TP
temporal\-tui\-filter\-save(1)
Save or replace a visibility query
.TP
temporal\-tui\-filter\-remove(1)
Remove a saved visibility query
